### ISSUE TITLE
Deadkeys on Linux panics

### ISSUE THREAD

**Issue by Cyres** [tomaka/winit#366]
On X11, even the most simple program crashes, when using a dead key. For example when inputting `^ + a`, which should result in `â`. I used the german layout. and tested with latest version and with master.:

```thread 'main' panicked at 'attempt to subtract with overflow'```
[`src/platform/linux/x11/mod.rs:415:35`](https://github.com/tomaka/winit/blob/8f18dab06108592b04bda260be30b9b912a67d43/src/platform/linux/x11/mod.rs#L410-L419)

**Comment by francesca64** [comment]
I've created [a branch where dead keys are handled correctly](https://github.com/francesca64/winit/tree/x11-kb-rewrite) (at least, as far as I can tell). Could you try it and let me know if it's satisfactory?

**Comment by Cyres** [comment]
This works as intended, thank you. 
Sidenote: The package `libxkbcommon-x11-0` is not sufficient for Ubuntu, I had to install `libxkbcommon-x11-dev`.

**Comment by tbu-** [comment]
I also get this when using the compose key: `compose key, ´, a` and the program crashes.

```
thread 'main' panicked at 'attempt to subtract with overflow', .cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.9.0/src/platform/linux/x11/mod.rs:294:35
```

**Comment by francesca64** [comment]
@tbu- this issue isn't resolved in master yet, as I've been a bit busy lately. I encourage you to try [the branch I linked to above](https://github.com/francesca64/winit/tree/x11-kb-rewrite), since it's a significant change that would benefit from further testing.

**Comment by dbluhm** [comment]
I'm indirectly using winit through Alacritty and ran into this problem when attempting to input Korean characters. Below is Alacritty's dependency list:
```toml
[dependencies]
libc = "0.2"
cgmath = "0.16"
notify = "4"
bitflags = "1"
font = { path = "./font" }
errno = "0.2"
parking_lot = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
vte = "0.3"
mio = "0.6"
mio-more = "0.1"
copypasta = { path = "./copypasta" }
xdg = "2"
log = "0.4"
clap = "2"
fnv = "1"
unicode-width = "0.1"
arraydeque = "0.2"
glutin = "0.12"
clippy = { version = "*", optional = true }
env_logger = "0.5"
base64 = "0.9.0"
```

From what I could gather, glutin is the crate pulling winit in so I attempted manually specifying your branch as a dependency as follows:

```toml
[dependencies]
#...
arraydeque = "0.2"
winit = {git = "https://github.com/francesca64/winit", branch = "x11-kb-rewrite"}
glutin = "0.12" #winit dep is here
clippy = { version = "*", optional = true }
#...
```
I'm still not totally familiar with how Cargo handles dependencies so I totally understand if this was a naive and incorrect attempt lol but I still ended up hitting the same panic as before.

Backtrace:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:415:35
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: winit::platform::platform::x11::EventsLoop::process_event
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:415
  11: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:162
  12: winit::platform::platform::EventsLoop::poll_events
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/mod.rs:396
  13: winit::EventsLoop::poll_events
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/lib.rs:221
  14: alacritty::window::Window::poll_events
             at ./src/window.rs:270
  15: <alacritty::event::Processor<N>>::process_events
             at ./src/event.rs:427
  16: alacritty::run
             at src/main.rs:179
  17: alacritty::main
             at src/main.rs:62
  18: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

See https://github.com/jwilm/alacritty/issues/1113 for my original issue.

**Comment by dbluhm** [comment]
I'm indirectly using winit through Alacritty and ran into this problem when attempting to input Korean characters. Below is Alacritty's dependency list:
```toml
[dependencies]
libc = "0.2"
cgmath = "0.16"
notify = "4"
bitflags = "1"
font = { path = "./font" }
errno = "0.2"
parking_lot = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
vte = "0.3"
mio = "0.6"
mio-more = "0.1"
copypasta = { path = "./copypasta" }
xdg = "2"
log = "0.4"
clap = "2"
fnv = "1"
unicode-width = "0.1"
arraydeque = "0.2"
glutin = "0.12"
clippy = { version = "*", optional = true }
env_logger = "0.5"
base64 = "0.9.0"
```

From what I could gather, glutin is the crate pulling winit in so I attempted manually specifying your branch as a dependency as follows:

```toml
[dependencies]
#...
arraydeque = "0.2"
winit = {git = "https://github.com/francesca64/winit", branch = "x11-kb-rewrite"}
glutin = "0.12" #winit dep is here
clippy = { version = "*", optional = true }
#...
```
I'm still not totally familiar with how Cargo handles dependencies so I totally understand if this was a naive and incorrect attempt lol but I still ended up hitting the same panic as before.

Backtrace:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:415:35
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: winit::platform::platform::x11::EventsLoop::process_event
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:415
  11: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:162
  12: winit::platform::platform::EventsLoop::poll_events
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/mod.rs:396
  13: winit::EventsLoop::poll_events
             at /home/dbluhm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/lib.rs:221
  14: alacritty::window::Window::poll_events
             at ./src/window.rs:270
  15: <alacritty::event::Processor<N>>::process_events
             at ./src/event.rs:427
  16: alacritty::run
             at src/main.rs:179
  17: alacritty::main
             at src/main.rs:62
  18: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

See https://github.com/jwilm/alacritty/issues/1113 for my original issue.

**Comment by francesca64** [comment]
@dbluhm I think that would only work if you'd changed the dependency within glutin. Try adding this section to your Alacritty Cargo.toml:
```toml
[patch.crates-io]
winit = { git = "https://github.com/francesca64/winit", branch = "x11-kb-rewrite" }
```
and if that still doesn't work, then throw in a `cargo update` for good measure.
